### ISSUE TITLE
@Dynamic deferred  with @SubjectPresent

### ISSUE THREAD

**Issue by dnul** [schaloner/deadbolt-2#31]
Hi, I'm currently using this version:  "be.objectify" %% "deadbolt-java" % "2.1-RC2" in a play 2.1 app, I'm having issues using both @Dynamic(deferred=true) at method-level with @SubjectPresent at controller level.

I modified the sample project in github to test this:

    @SubjectPresent   
    @DeferredDeadbolt
    public class DeferredController extends Controller
    ....
    @Dynamic(value="pureLuck2", deferred=true)
    public static Result deferredDynamic()
    {
        return ok(accessOk.render());
    }

then in the MyDynamicResourceHandler I added:

    HANDLERS.put("pureLuck2",
    new AbstractDynamicResourceHandler()
                {
                    public boolean isAllowed(String name, 
                                             String meta, 
                                             DeadboltHandler deadboltHandler,
                                             Http.Context context)
                    {
                        return System.currentTimeMillis() % 2 == 0/0;
                    }
                });

notice the division by zero, this is to test if the handler is being executed(it should crash every time). 
Whether I put @SubjectPresent   or @SubjectNotPresent at the top of the controller I still get an error page in the little iframe corresponding to this test.  What I understand from this is that the Dynamic handler is being executed always first, when it shouldn't be executed at all. 

Thanks

**Comment by schaloner** [comment]
Method annotations take precedence over class annotations, so the execution of the method annotation is as expected. 

For a class like this

    @Dynamic(name = "foo")
    public class MyController extends Controller {
        @Dynamic(name = "bar")
        public Result index() {...}
    }

Only `bar` will execute, immediately or deferred.  If it fails, authorization is blocked and `foo` will not be invoked.

**Comment by mkurz** [comment]
@tomasu82 my pull request https://github.com/schaloner/deadbolt-2-java/pull/50 addresses your issue:
By setting `deadbolt.java.constraint-mode = "AND"` all the constraints would be chained and the action method would only run if **all** the constraints are succesful.

Also in Play you are now able to influence to order which annotations will be called first (the method ones or the controller ones) by setting
`play.http.actionComposition.controllerAnnotationsFirst = true`.
