### ISSUE TITLE
Scala documentation

### ISSUE THREAD

**Issue by 13h3r** [schaloner/deadbolt-2#34]
It will be good to fill https://github.com/schaloner/deadbolt-2-guide/blob/master/09-deadbolt-scala-templates.markdownm and https://github.com/schaloner/deadbolt-2-guide/blob/master/10-deadbolt-scala-controllers.markdown

**Comment by schaloner** [comment]
Agreed - take a look at those links, and the resulting book at https://leanpub.com/deadbolt-2
