### ISSUE TITLE
How to disable deadbolt for functional test on controllers ?

### ISSUE THREAD

**Issue by larousso** [schaloner/deadbolt-2#36]
Hi, 

I use deadbolt in my app but I am blocked in my functional test when I want to test some rest api that are restrict. 
Is it possible to disable deadbolt or to authenticate a fake user for ths kind of tests ? 

Thanks

**Comment by anunpn** [comment]
@schaloner , can you please explain this solution in detail?

**Comment by schaloner** [comment]
@anunpn how many handlers do you have?

**Comment by anunpn** [comment]
Let me explain you the details very quickly.

At controller, 

def performAction = AuthAction(“perm”).async(parse.json[Request])


trait AuthAction extends DeadboltActions {

class Request[A](val userInfo : UserInfo, request: Request[A]) extends WrappedRequest[A](request)

  def subjectPresentHandler = new AuthSubjectPresentHandler
  def permissionPatternHandler = new AuthPermissionPatternHandler
  
 def AuthAction[A](permission : String) = new ActionBuilder[Request] {
def invokeBlock[A](request: Request[A], block: (Request[A]) => Future[Result]) = {
						var userInfo : UserInfo = null 
			val sessionId : Option[String] = request.session.get("sessionId")
			

			sessionId match {
			   case Some(id) =>
			     	val sessionObj = Cache.get(id)
			     	if(sessionObj != null){
			     		userInfo = sessionObj.asInstanceOf[User].userInfo  
			     		println("Retrieving it from session **********************")
			     	} else {
			     		subjectPresentHandler.onAuthFailure(request)  
			     	}
			     	
			   case None =>
			     subjectPresentHandler.onAuthFailure(request)- MY SCALATEST fails here.
			}
			
			block(new Request(userInfo, request))
	  	}

      override def composeAction[A](action: Action[A]) = SubjectPresent(subjectPresentHandler)  (
	  															(Pattern(permission, PatternType.EQUALITY, permissionPatternHandler)(action)) )

	}
   		
}

**Comment by anunpn** [comment]
thanks in advance

**Comment by schaloner** [comment]
Wouldn't it make more sense to manipulate the request to provide a session ID?  Disabling Deadbolt here would fundamentally change how your code works.
