### ISSUE TITLE
Better support for DI

### ISSUE THREAD

**Issue by FrEaKmAn** [schaloner/deadbolt-2#43]
Hello

I'm using Dependency Injection together with Spring repositories. So basically I inject repository to access database data. Using your code, I want to inject into SecurityHandler which extends AbstractDeadboltHandler, so I can use it in getSubject method. Are there any good ways to accomplish this?

At the moment, I'm solving it with

    @Override
    public Subject getSubject(Http.Context context)
    { 
        String email = context.session().get("email");
        
        UserRepository userRepository = Play.current().global().getControllerInstance(UserRepository.class);
        User user = userRepository.findByEmail(email);
        
        return user;
    }

but I'm not sure if this is good approach. Any tips?

**Comment by schaloner** [comment]
This will be implemented as of Deadbolt 2.4 to take advantage of the built-in DI support.
