### ISSUE TITLE
Is it possible to chain multiple restrictions?

### ISSUE THREAD

**Issue by vizog** [schaloner/deadbolt-2#54]
I was trying to combine multiple restrictions like this:

```
@Restrict(value = {@Group({"foo", "bar"})})
@Pattern(handlerKey = "pureLuck", value = "printers.printer")
public static Result test()
{
    return ok(accessOk.render());
}
```

The first check passes because the subject has "foo" and "bar" roles.
The second check doesn't pass if it is used alone (not after @Restrict)
I expect the overall check not to pass, but it does pass and the content is rendered.
I read the source and saw that, if a restriction is passed with an action (say the first @Restrict),
the request is marked as authorized ( markActionAsAuthorised(ctx);) and when the next delegate is called (in this case @Pattern), it first checks if the request has already been authorized ( isActionAuthorised(ctx) ) and if so, it passes to the next delegate without processing the request.
This can be found at AbstractRestrictiveAction class line 37.
I wonder if this is intended? I believe it can be much more beneficial if we can chain the authorization actions and fail if any of them fail. But currently we only process the first action actually.

**Comment by mkurz** [comment]
My pull request https://github.com/schaloner/deadbolt-2-java/pull/50 addresses exactly this issue here:
By setting `deadbolt.java.constraint-mode = "AND"` all the constraints would be chained and the action method would only run if all the constraints are succesful.

**Comment by mkurz** [comment]
(updated my comment)
