### ISSUE TITLE
Multiple levels of @Restrict

### ISSUE THREAD

**Issue by aeusebio** [schaloner/deadbolt-2#57]
Hi there, I'm trying to authorize a client and a user.

For instance, only clients with the role "api" can access the actions of the controller "Api", and within the controller, only the users with the role "admin"  can access the action "foo".

Example:
```java
@Restrict(value=@Group("api"), handlerKey="client")
public class Api extends Controller {
	@Restrict(value=@Group("admin"), handlerKey="user")
	public static Result foo(){
		return ok();
	}
}
```

The issue is that the @Restrict tag uses always the last handler called to check the subject. In the example above, the user handler is always called twice, where it should be called the client handler and then the user handler.

Best regards

**Comment by schaloner** [comment]
Hmm, each invocation should use the locally defined handler (or the default handler if nothing is specified).  But, if the Restrict on the foo() method passes, the outer restrict won't be applied (i.e. the most specific restriction takes priority).

**Comment by schaloner** [comment]
If you want to restrict foo() to users with the "api" and "admin" roles, the Group definition of foo() should be 

    @Group({"api", "admin"})

**Comment by aeusebio** [comment]
Ok, but I need to authorize a client and a user (the user interacts with my system using a client).

Imagine, I want some controllers to be accessed by a specific client, and I want to specify, which users can access which actions of those controllers.

For instance, I want my client "foo" to have access to all the controllers, but my client "foo2" to only have access to one of the controllers. On another hand, I can have users with different roles interacting with my system using each of these clients. 
Let's say that I want a user with the role "admin" to have access to all the actions, but a user with the role "user" to have access to only one of the actions. How can I use deadbolt to implement this kind of architecture?

```java
@Restrict(value=@Group({"foo", "foo2"}), handlerKey="client")
public class Controller1 extends Controller {
    @Restrict(value=@Group("admin"), handlerKey="user")
    public static Result foo1(){
        return ok();
    }
    @Restrict(value=@Group({"admin","user"}), handlerKey="user")
    public static Result foo2(){
        return ok();
    }
}

@Restrict(value=@Group("foo"), handlerKey="client")
public class Controller2 extends Controller {
    @Restrict(value=@Group("admin","user"), handlerKey="user")
    public static Result xpto(){
        return ok();
    }
    @Restrict(value=@Group("admin"), handlerKey="user")
    public static Result xpto2(){
        return ok();
    }
}
```

Another issue, have you guys tried deadbolt2 with JPA?
If you put the restrict annotation in the controller, you can't use the transaction annotation in the actions.

**Comment by schaloner** [comment]
I think that instead of using Restrict, you might be better off using Dynamic - this leaves you completely free to define your own constraints.

WRT the JPA issue, I have seen people suggest you put the Transactional annotation before the Deadbolt annotations.  Alternatively, you can wrap your code in an annotation manually in the controller (which is annoying).

**Comment by aeusebio** [comment]
Ok, I'm going to do that. But it would be nice if in runtime the annotations could respect the handlerKey's given to them.

WRT the JPA, that was the solution that I implemented. I believe the problem is more in the Play Framework side than the deadbolt. 

Anyway, thanks for your help.

**Comment by schaloner** [comment]
I'm looking at the handler key issue - it's quite weird, because each action is configured by the annotation that invokes it so there shouldn't be any bleed between them.  Let me know if you have any more issues, and good luck!
