### ISSUE TITLE
Play 2.4 support

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2#58]
Hi,

Are you going to support Play 2.4 and dependency injection?
So far the error message says:

<code>
Could not find a suitable constructor in be.objectify.deadbolt.java.DeadboltPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at be.objectify.deadbolt.java.DeadboltPlugin.class(Unknown Source)
  while locating be.objectify.deadbolt.java.DeadboltPlugin
</code>

Kind regards

**Comment by keepscoding** [comment]
me too. hope it will ready before the 2.4 release

**Comment by nafg** [comment]
+1

**Comment by schaloner** [comment]
It's in progress at the moment.

**Comment by schaloner** [comment]
`"be.objectify" %% "deadbolt-java" % "2.4.0-SNAPSHOT"` should give what you you're looking for.  Documentation coming later today, but the release notes on https://github.com/schaloner/deadbolt-2-java should be enough to get you started.

**Comment by eximius313** [comment]
::::::::::::::::::::::::::::::::::::::::::::::
::          UNRESOLVED DEPENDENCIES         ::
::::::::::::::::::::::::::::::::::::::::::::::
:: be.objectify#deadbolt-java_2.11;2.4.0-SNAPSHOT: not found
::::::::::::::::::::::::::::::::::::::::::::::

**Comment by schaloner** [comment]
You probably need to add a resolver for the snapshot repo in your build.sbt

    resolvers += Resolver.sonatypeRepo("snapshots")

**Comment by eximius313** [comment]
yes, you were right

**Comment by eximius313** [comment]
I didn't have it, but adding it unfortunatelly didn't work :(
```
[info] Resolving be.objectify#deadbolt-java_2.11;2.4.0-SNAPSHOT ...
[warn]  module not found: be.objectify#deadbolt-java_2.11;2.4.0-SNAPSHOT
[warn] ==== local: tried
[warn]   C:\Users\user\.ivy2\local\be.objectify\deadbolt-java_2.11\2.4.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== activator-local: tried
[warn]   C:\Users\user\activator-1.3.2\repository\be.objectify\deadbolt-java_2.11\2.4.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/be/objectify/deadbolt-java_2.11/2.4.0-SNAPSHOT/deadbolt-java_2.11-2.4.0-SNAPSHOT.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/be/objectify/deadbolt-java_2.11/2.4.0-SNAPSHOT/deadbolt-java_2.11-2.4.0-SNAPSHOT.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/be.objectify/deadbolt-java_2.11/2.4.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/be/objectify/deadbolt-java_2.11/2.4.0-SNAPSHOT/deadbolt-java_2.11-2.4.0-SNAPSHOT.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/be/objectify/deadbolt-java_2.11/2.4.0-SNAPSHOT/deadbolt-java_2.11-2.4.0-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: be.objectify#deadbolt-java_2.11;2.4.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by schaloner** [comment]
Damn, there's a problem with the Travis build script.  I'm re-running it now, will let you know when it's done.

**Comment by schaloner** [comment]
@eximius313 OK, it's published: 

https://oss.sonatype.org/#nexus-search;gav~be.objectify~deadbolt-java_2.11~2.4.0-SNAPSHOT~~

**Comment by eximius313** [comment]
It works!
I'm waiting for the updated documentation to start my deadbolt-2 adventure ;)
Thank you so much ;)

**Comment by schaloner** [comment]
The old docs are still good, you just have to follow the interface/trait contract.

If a method returns, say, an F.Promise<Optional<Subject>> and you want it to be null then don't return null or a promise that completes to null.  Instead, return F.Promise.pure(Optional::empty)

If a method returns, say, F.Promise<Boolean>, then it can not complete to null (because it's not an optional type), don't return a null or a promise that completes to null. Instead, return F.Promise.pure(false).  And by false, I mean whatever your default authorisation policy is - true doesn't really make any sense here.

Finally, if you have any issues then either create an issue here or mail me directly.

Good luck (although hopefully you won't need it)!

**Comment by schaloner** [comment]
@eximius313 Take a look at https://github.com/schaloner/deadbolt-2-java-examples for some usage and set-up examples.

**Comment by eximius313** [comment]
Steve,

Everything works like a charm - thank you very much!
My only one concern is how to use ```@Dynamic``` with ```@Restrict``` combined.
Can you point me to an example or documentation about it?

Kind regards

**Comment by eximius313** [comment]
And by the way - the same error occurred again today:
https://github.com/schaloner/deadbolt-2/issues/58#issuecomment-108845004

**Comment by schaloner** [comment]
It's not handled at the moment, but I'm working on it.  Now I don't need to support < Java 8, things will be a lot easier to achieve.

**Comment by eximius313** [comment]
Great!
Thank you!

**Comment by eximius313** [comment]
I've come up with some idaes concerning ```@Dynamic``` and ```@Restrict```: https://github.com/schaloner/deadbolt-2/issues/9#issuecomment-109798535

**Comment by nafg** [comment]
Is there a final release for play 2.4? If not when?

**Comment by schaloner** [comment]
@nafg there are still some features to be added, primarily support for https://github.com/schaloner/deadbolt-2/issues/9#issuecomment-109798535 but if I can't find a non-breaking solution in the next couple of days I'll make a final release and shift that feature to 2.4.1.

This is applicable for both Scala and Java versions.

**Comment by zarubto4** [comment]
Hello @schaloner, Thank you for deadbolt. But I still did not find anything about #9  , if you solved the combination @Dynamic OR @Restrict and also  @Dynamic AND @Restrict.

**Comment by schaloner** [comment]
I've played around with a few different ideas to handle this.  Fitting it into an annotation-based approach and not have it be horribly complicated is proving tricky, but I have something that looks promising.

**Comment by eximius313** [comment]
Great! :+1:
