### ISSUE TITLE
Specify handlerKey for the @restrict(la(as("foo"))) template

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2#60]
While using ```@Restrict``` annotation one can specify ```handlerKey``` property.
I have read somewhere that this handler, once instantiated, is being cached.
Is it true?
If yes - it should be possible to specify handlerKey for the ```@restrict(la(as("foo")))``` template

So far I have found a workaround:
```@restrictOr(la(as("foo", "bar"), as("hurdy")), new com.example.SomeSpecificDeadboltHandler())```
but there, you must create new handler for each invocation, which is not optimal.

**Comment by schaloner** [comment]
Handlers are eagerly created and cached, and held in the HandlerCache instance.  You can inject this into your controllers, get the desired handler from there and then pass it into the template as a parameter.

Simple example:

    public class MyController extends Controller {
        private final HandlerCache handlerCache;
        
        @Inject
        public MyController(final HandlerCache handlerCache) {
            this.handlerCache = handlerCache;
        }
        
        public static F.Promise<Result> foobar() {
            return F.Promise.promise(() -> myPage.render(handlerCache.get("alternativeHandler")))
                            .map(content -> ok(content))
        } 
    }

In your template, you would then have

    @(handler: DeadboltHandler)
    
    @restrictOr(la(as("foo", "bar"), as("hurdy")), handler) {
        // protected content
    } {
        // fallback content
    }

**Comment by schaloner** [comment]
This approach also means you're not hard-coding handler choice into the templates, and so you get more flexibility.

**Comment by eximius313** [comment]
yeah, but if you allow to configure "handlerKey" in ```@Restrict``` then it would be nice and *consistent* across the API if ```@restrict``` would also allow to do it.
And last, but not least - even if I pass this handler to the template, I have to create/inject/find it somewhere else anyway so I loose the benefit of defining it in application.conf.

**Comment by eximius313** [comment]
By the way - which of these websites is most up-to-date:
http://deadbolt.ws/#/java-docs or http://deadbolt-2-java.herokuapp.com/#controller-Restrictions ?

**Comment by schaloner** [comment]
I'll have a think about this - I'll need to do it in the least invasive way, but it's a good idea and now is the time to make breaking changes if they have to be made.

deadbolt.ws is the most up to date, but it's not been reworked for 2.4 yet.  https://github.com/schaloner/deadbolt-2-java-examples is the most up to date - this is the app which runs on heroku, but it hasn't been deployed there yet.

**Comment by eximius313** [comment]
So in http://deadbolt.ws/#/java-docs look at the  ```Define a DeadboltHandler in the template```  subsection under the ```restrict``` section and compare it to the same subsection under the ```dynamic``` section. Is this correct?

If its about http://deadbolt-2-java.herokuapp.com/#controller-Restrictions
In 2.4 version I can not find ```@And``` and ```@Restrictions``` is this correct?

**Comment by schaloner** [comment]
Doc error fixed, thanks.

`And` and `Restrictions` are gone - there's now a single `Restrict` constraint that handles this.  `And` was replaced by `Group`.

**Comment by schaloner** [comment]
Use `@import be.objectify.deadbolt.java.ViewAccessPoint.Implicits._` to get the handler cache, and you can then call `apply` on it with a handler key.

~~~
@import be.objectify.deadbolt.java.ViewAccessPoint.Implicits._
@import be.objectify.deadbolt.java.views.html._
    
@dynamicOr(name = "pureLuck", handler = handlerCache.apply(HandlerKeys.ALT.key)) {
    This content should NOT be visible
}{Guess you were unlucky}
~~~

In this example, taken from [here](https://github.com/schaloner/deadbolt-2-java-examples/blob/master/app/views/examples/templates/Dynamic.scala.html), `HandlerKeys` is an enum.

~~~
public enum HandlerKeys
{
    DEFAULT(ConfigKeys.DEFAULT_HANDLER_KEY),
    ALT("altHandler"),
    BUGGY("buggyHandler"),
    NO_USER("noUserHandler");

    public final String key;

    private HandlerKeys(final String key)
    {
        this.key = key;
    }
}
~~~
