### ISSUE TITLE
using @templates with cache-user=false causes IllegalArgumentException: Not an entity: class domain.User after recompilation

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2#61]
If you set cache-user=false in application.conf and you use annotations on methods everything works fine: you can modify class/template, recompile and refresh the page.
Unfortunately, when you try to use templates (```@restrict(la(as("MY_ROLE")))``` for example) and you modify class/template, recompile and refresh the page you obtain weird exception:
```
[IllegalArgumentException: Not an entity: class domain.User]
			CriteriaBuilder criteriaBuilder = JPA.em().getCriteriaBuilder();
			CriteriaQuery<User> query = criteriaBuilder.createQuery(User.class);
			Root<User> root = query.from(User.class); <---- THIS LINE IS HIGHLIGHTED
			query.select(root);
			query.where(criteriaBuilder.equal(root.get(FIELD_EMAIL),email));
			return Optional.of(JPA.em().createQuery(query).getSingleResult());
```

**Comment by eximius313** [comment]
This ALSO happens with JPQL
```User result = find.where().eq(User.FIELD_EMAIL, email).findUnique();```

**Comment by schaloner** [comment]
This only happens after recompilation?  If you start  your app with `cache-user=false`,`it works correctly?

**Comment by eximius313** [comment]
Yes.
If this exception occurs, I do ```ctrl+D``` and ```run``` again.
This works, but after 2-3 restarts I have this error: https://github.com/playframework/playframework/issues/4617
Without using template restrictions above error doesn't occur.

**Comment by schaloner** [comment]
What happens if you:
- don't define cache-user=false  (just remove the entry from application.conf
- use cache-user=true instead

**Comment by eximius313** [comment]
When you don't define it, the situation is the same.
With cache-user=true it happens rarely.
Steps to reproduce:
1)put code in template:
```
@*
@restrict(la(as("MY_ROLE"))){
  something
}
*@
```
2)load the page
3)uncomment, refresh page
4)enter new line, refresh page

**Comment by eximius313** [comment]
Have you managed to reproduce the error?

**Comment by mkurz** [comment]
I have the same problem using `deadbolt-java` `2.4.0-SNAPSHOT` with Play 2.4.1:
`@subjectPresentOr()` in a template causes the app to crash as soon you as change something and trigger a recompilation.

@schaloner Any thoughts?

**Comment by schaloner** [comment]
I've managed to damage both my thumbs so I'm out of action for a couple of days. Will look at it asap.

**Comment by mkurz** [comment]
@schaloner Get well soon!

**Comment by eximius313** [comment]
Oh! I hope you'll be alright soon!

**Comment by schaloner** [comment]
3-fingered typing leaves something to be desired!

I suspect the issue is caused by https://github.com/schaloner/deadbolt-2-java/blob/master/code/app/be/objectify/deadbolt/java/ViewAccessPoint.java which is a hack to get around no DI in templates.

**Comment by schaloner** [comment]
I've found the issue - I'll commit the fix, update the examples, etc, this evening.  I'll update here when it's done.

**Comment by eximius313** [comment]
Great news!
Thank you so much!!

**Comment by schaloner** [comment]
The problem is due to a static reference to a managed instance:

    public class ViewAccessPoint {
        public final static ViewSupport VIEW_SUPPORT;
        public final static HandlerCache HANDLERS;
    
        static {
            final Injector injector = Play.application().injector();
            VIEW_SUPPORT = injector.instanceOf(ViewSupport.class);
            HANDLERS = injector.instanceOf(HandlerCache.class);
        }
    }

The trick is to not have static references (preferably anywhere, in fact) and instead use a Scala object with implicits to access the managed instances.

    object ViewAccessPoint {
        private[deadbolt] val viewStuff = Application.instanceCache[ViewSupport]
        private[deadbolt] val handlerStuff = Application.instanceCache[HandlerCache]
    
        object Implicits {
            implicit def viewSupport(implicit application: Application): ViewSupport = viewStuff(application)
            implicit def handlerCache(implicit application: Application): HandlerCache = handlerStuff(application)
        }
    }

In the views, this changes

    @import be.objectify.deadbolt.java.DeadboltHandler
    @import be.objectify.deadbolt.java.ViewAccessPoint.{HANDLERS, VIEW_SUPPORT}
    @(name: String, meta: String = null, handler: DeadboltHandler = HANDLERS.get(), timeout: java.util.function.Supplier[Long] = VIEW_SUPPORT.defaultTimeout)(body: => Html)

    @if(VIEW_SUPPORT.viewDynamic(name, meta, handler, timeout.get())) {
        @body
    }

to

    @import play.api.Play.current
    @import be.objectify.deadbolt.java.DeadboltHandler
    @import be.objectify.deadbolt.java.ViewAccessPoint.Implicits._
    @(name: String, meta: String = null, handler: DeadboltHandler = handlerCache.get(), timeout: java.util.function.Supplier[Long] = viewSupport.defaultTimeout)(body: => Html)
    
    @if(viewSupport.viewDynamic(name, meta, handler, timeout.get())) {
    @body
    }

**Comment by mkurz** [comment]
@schaloner NIce - I am happy to test a new `SNAPSHOT` :smile:

**Comment by schaloner** [comment]
Excellent - once this fix is in and you're satisfied with it, I'm going to cut (and tag) the 2.4.0 final.   (Combining constraints will have to wait for 2.4.1.)

**Comment by schaloner** [comment]
@eximius313 @mkurz v2.4.0 is released, plus the sample app is updated.

If you're using the Scala version, the latest is now 2.4.0.2.

Please let me know if you have any issues, and thanks for all your feedback!

**Comment by mkurz** [comment]
I will upgrade tomorrow and let you know if any issues appear. Thanks!

**Comment by eximius313** [comment]
This works for me!
Thank you so much @schaloner !!
