### ISSUE TITLE
CreationException: Unable to create injector

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2#63]
Newest deadbolt snapshot:

```
CreationException: Unable to create injector, see the following errors:

1) No implementation for be.objectify.deadbolt.java.cache.HandlerCache was bound.
  while locating be.objectify.deadbolt.java.cache.HandlerCache
    for parameter 3 at be.objectify.deadbolt.java.ViewSupport.<init>(ViewSupport.java:70)
  at be.objectify.deadbolt.java.DeadboltModule.viewSupport(DeadboltModule.java:48):
Binding(class be.objectify.deadbolt.java.ViewSupport to self in interface javax.inject.Singleton) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error
```

**Comment by schaloner** [comment]
Did you create and expose your own HandlerCache implementation as in the [quickstart guide](https://github.com/schaloner/deadbolt-2-java/blob/master/QuickStart.md)?

**Comment by eximius313** [comment]
No, I just use cache-user=true as before
24 cze 2015 08:11 "Steve Chaloner" <notifications@github.com> napisał(a):

**Comment by eximius313** [comment]
No, I just use cache-user=true as before
Is it necessary to create own implementation?

**Comment by eximius313** [comment]
I see that in version 2.4.0 there is no class that implements be.objectify.deadbolt.java.cache.HandlerCache

Is it on purpose?

**Comment by schaloner** [comment]
Yes, because it means reflection doesn't have to be used to create instances of handlers; it gives you a lot more flexibility.

You can see an example here: https://github.com/schaloner/deadbolt-2-java-examples/blob/master/app/security/MyHandlerCache.java

**Comment by eximius313** [comment]
I see that in version 2.4.0 there is no class that implements be.objectify.deadbolt.java.cache.HandlerCache

Is it on purpose?

**Comment by schaloner** [comment]
See also this discussion: https://groups.google.com/d/topic/play-framework/KZcCdbWZXvQ/discussion

**Comment by eximius313** [comment]
OK, so If I understood it well - custom HandlerCache is required now?

**Comment by schaloner** [comment]
Yes.  This also provides info and background: https://github.com/schaloner/deadbolt-2-guide/blob/master/manuscript/04-deadbolt-java-hooks.md

**Comment by eximius313** [comment]
OK, understood.
Snapshot was working fine without custom Cache, that is why I was a little bit confused.
Thank you for helpful links. With custom cache it works fine
