### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by osek666** [schaloner/deadbolt-2#64]
Hi! I new in play and deadbolt and I have simple question.
I have controler with action

```java
public class Application extends Controller {

    @SubjectPresent
    public Result index() {
        return ok(index.render("Your new application is ready."));
    }

}
```

I get "403 Authorization failed" in browser and it is perfectly clear beacause I'm not logged in. But I also have error in logs

```
[error] - be.objectify.deadbolt.java.actions.AbstractDeadboltAction - Access to [/] requires a subject, but no subject is present.
``` 

It is normal or I implemented something wrong?

**Comment by schaloner** [comment]
That's absolutely normal.  You can find the relevant code here: https://github.com/schaloner/deadbolt-2-java/blob/master/code/app/be/objectify/deadbolt/java/actions/AbstractDeadboltAction.java#L193

**Comment by osek666** [comment]
Yes, I saw it.
And you think this kind of action (restricting access) is application error?

**Comment by schaloner** [comment]
Sorry for the delay, I've been on vacation.

If you're using Play 2.4, you can update your Deadbolt dependency to `"be.objectify" %% "deadbolt-java" % "2.4.1"` - this changes the logging level on this line to ´info´.

**Comment by osek666** [comment]
Thanks!
