### ISSUE TITLE
Opposite of @Pattern

### ISSUE THREAD

**Issue by sirsavary** [schaloner/deadbolt-2#66]
I was wondering if an annotation could be implemented to deny a user access if they have a certain permission. SubjectNotPresent already exists so I don't see why not. I'd like this functionality so I can grant all users all functionality by default and then use permissions to ban them from certain areas of the site.

**Comment by schaloner** [comment]
This can be added as an attribute of the constraint.  It'll be in the next release.

**Comment by sirsavary** [comment]
Fantastic! Thank you very much for your work on this.

**Comment by schaloner** [comment]
This feature is in `"be.objectify" %% "deadbolt-java" % "2.4.2-SNAPSHOT"` (don't forget to add the snapshot repo) if you want to try it out.  

`@Pattern(..., invert = true)`

Would you be interested in having your project listed on http://deadbolt.ws/#/home ?

**Comment by schaloner** [comment]
This has been released as "be.objectify" %% "deadbolt-java" % "2.4.2"

**Comment by sirsavary** [comment]
Awesome! This is going to make managing my site a million times easier. I'd also love to have my project listed, anyway I can get that information to you?

**Comment by schaloner** [comment]
Sure, you can email deadbolt@objectify.be and me know the details.

**Comment by schaloner** [comment]
I spotted a bug in this earlier, so make sure you use 2.4.2.1-SNAPSHOT - I'll release the final version of this in about 7 hours.

Are you using PatternType.CUSTOM constraints?

**Comment by schaloner** [comment]
@sirsavary I spotted a bug in this earlier, so make sure you use 2.4.2.1-SNAPSHOT - I'll release the final version of this in about 7 hours.

Are you using PatternType.CUSTOM constraints?
