### ISSUE TITLE
Play 2.4 installation

### ISSUE THREAD

**Issue by nem25** [schaloner/deadbolt-2#69]
I feel really ridiculous about this but I just can't get the deadbolt packages to register on Play. I'm using IntelliJ and the full description of my problem is here - [stackoverflow](http://stackoverflow.com/questions/35386580/play-2-4-and-deadbolt-installation)

Any help would be much appreciated!

**Comment by schaloner** [comment]
The READMEs of both the Scala and Java versions have been updated to be useful, in both the 2.4 and master branches.  I hope this helps!

**Comment by nem25** [comment]
Yes thanks! Some ppl on stack helped me too!
