### ISSUE TITLE
Deadbolt timeout using Play 2.5

### ISSUE THREAD

**Issue by umbreak** [schaloner/deadbolt-2#70]
This is related with the [issue described in Stackoverflow](http://stackoverflow.com/questions/36142724/play-framework-2-5-0-java-blocked-netty-event-loop-threads-resulting-in-time)

Deadbolt Deadbolt-java 2.5.0-SNAPSHOT: timeout messages in our logs related to Deadbolt

**Comment by schaloner** [comment]
Can you share any details of what you're using (controller constraints, template constraints, etc), implementations of DeadboltHandler, etc?

**Comment by schaloner** [comment]
According to the comments on http://stackoverflow.com/q/36142724/1063929 the issue is not related to Deadbolt.

See https://github.com/playframework/playframework/issues/5972 for the bug report.
