### ISSUE TITLE
problems when using AuthenticateRequest

### ISSUE THREAD

**Issue by scweang** [schaloner/deadbolt-2#71]
I found it is a little difficult to use deadbolt with custom Actions such as a simple action which extends ActionBuilder.

For example, I have a multiple-tenant system. Each valid request contains not only user info, but also the tenant this user belongs to. So I have a TenantRequest which extends WrappedRequest and have a member named tenant.

However, when I want to use deadbolt to do permission check, it is really difficult for me to make tenant be seen in the action. I have to change the source code as below:

```scala
class AuthenticatedRequest[+A](val subject: Option[Subject], val request: Request[A]) extends WrappedRequest[A](request)

object AuthenticatedRequest {
  def apply[A](r: Request[A], s: Option[Subject]) = new AuthenticatedRequest[A](s, r)
}
```

And with an ugly implicit conversion like:

```scala
  implicit def authRequest2TenantRequest[A](authenticatedRequest: AuthenticatedRequest[A]): TenantRequest[A] = {
    authenticatedRequest.request.asInstanceOf[AuthenticatedRequest[A]].request.asInstanceOf[TenantRequest[A]]
  }
```

I'm wondering why it is so difficult for me to compose actions. And I think this can be fixed and all deadbolt actions can be compose like all kinds of compositions this [document](https://www.playframework.com/documentation/2.5.x/ScalaActionsComposition) describes. Thank you~

**Comment by scweang** [comment]
Also, I think that the type of Subject might be more convenient if we can change it to its sub-type.

**Comment by schaloner** [comment]
I'm in the process of updating Deadbolt for exactly this reason.  I'll keep this question open until it's released and let you know when it's available.

**Comment by scweang** [comment]
Thanks for your response~~~I'm looking forward to apply deadbolt in my application~

**Comment by schaloner** [comment]
Moved to https://github.com/schaloner/deadbolt-2-scala/issues/26
