### ISSUE TITLE
Possibility to change severity of "Deadbolt: Access failure"

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2#74]
Whenever somebody tries to access protected resource and is not yet logged in, Deadbolt prints WARNING ```Deadbolt: Access failure``` 

It is a problem, because if user's session expired, he just loggs in again, but we have hundreds of this message in logs.

How to change it to "INFO" for example?
Kind regards

**Comment by schaloner** [comment]
No problem.  I'll make the changes (or you can submit a PR) and I'll release it this week.

**Comment by eximius313** [comment]
Hey @schaloner :)
Any news on this?

**Comment by schaloner** [comment]
Hi, sorry for the delay.  I've been looking at making this configurable without affecting performance so it wasn't just a straight switch of logging levels.  I'll push it out today.

**Comment by schaloner** [comment]
Although, it's the only non-exceptional warning in the code...I'll keep it simple and just change the level directly.

**Comment by schaloner** [comment]
This is available in 2.5.5-SNAPSHOT.  If no other issues come up by the end of the week, I'll cut the 2.5.5 release.

**Comment by eximius313** [comment]
Looks like everything is fine!

**Comment by schaloner** [comment]
Excellent.  I'll release this today.

**Comment by eximius313** [comment]
is it ```"be.objectify" %% "deadbolt-java" % "2.5.5"``` now?

**Comment by schaloner** [comment]
Should be, but I've just checked the release to Sonatype and it looks like there was a signing issue.  I'll look into it.

**Comment by schaloner** [comment]
I have no idea what happened, but it's finally available.  I had to create a new key to sign the artifacts with, and then it went through.

**Comment by mkurz** [comment]
Can be closed.
