### ISSUE TITLE
How long are Subjects cached in deadbolt?

### ISSUE THREAD

**Issue by markehammons** [schaloner/deadbolt-2#75]
Is there a way to make sure cached user information is updated if I know it needs updated?  Or is the cache time for users very short?

**Comment by schaloner** [comment]
If you enable user caching by setting `deadbolt.java.cache-user` to `true`, this caches the subject for the lifetime of the request.  It's an optimization that primarily benefits template constraints, which may be used multiple times within a single request.

**Comment by mkurz** [comment]
I think this can be closed.

**Comment by eximius313** [comment]
@mkurz I think it's a good idea to clarify that one in new docs as well

**Comment by mkurz** [comment]
@eximius313 Added to https://github.com/schaloner/deadbolt-2-java/issues/89: "Clarify how caching works..."
