### ISSUE TITLE
How to deviate between an Admin and a user using deadbolt

### ISSUE THREAD

**Issue by 030** [schaloner/deadbolt-2#76]
If a user is an admin, where does it need to be defined and if a user is a normal user?

**Comment by schaloner** [comment]
A user can have multiple roles - `Subject#roles` (Scala) and `Subject#getRoles` (Java) both return lists.  So, if you're using `Restrict`, a user who is both an admin and a user will have access to anything restricted to Restrict(admin) or Restrict(user).

**Comment by mkurz** [comment]
I think this issue can be closed.
