### ISSUE TITLE
Examples of usage with Play 2.6

### ISSUE THREAD

**Issue by yeryomenkom** [schaloner/deadbolt-2#77]
Could you provide some examples of using this plugin with playframework 2.6?

**Comment by mkurz** [comment]
Here are the docs:
https://deadbolt-java.readme.io/docs/
There is even a book you can read for free - however @schaloner would be very happy if you donate some cash :smile: 
https://leanpub.com/deadbolt-2

**Comment by mkurz** [comment]
I think we can close this issue.
