### ISSUE TITLE
Deadbolt non compatible with play 2.7

### ISSUE THREAD

**Issue by lenin122** [schaloner/deadbolt-2#78]
Cannot migrate, fails on dependency injections in deadbolt module.

**Comment by mkurz** [comment]
@lenin122 Are you using deadbolt-2-java or deadbolt-2-scala?

**Comment by lenin122** [comment]
deadbolt2-scala
also I'm trying to migrate to java 11

**Comment by mkurz** [comment]
https://github.com/schaloner/deadbolt-2-scala does not have support for Play 2.7 yet...
Someone has to update the project... You can provide a pull request if you want...

**Comment by mkurz** [comment]
Oh wait, someone did it, see: https://github.com/schaloner/deadbolt-2-scala/pull/44

**Comment by mkurz** [comment]
Closing this issue here.
