### ISSUE TITLE
Combining @Restrict and @Dynamic

### ISSUE THREAD

**Issue by joscha** [schaloner/deadbolt-2#9]
In Play 2.1-TRUNK the combination of @Restrict and @Dynamic does not seem to be possible.

I tried

```
@Restrict("user")
@Dynamic("dyn")
public static Result bla...
```

and I wanted the role user to be present and then check whether this user has access to the actual resource requested...

**Comment by eximius313** [comment]
+1

**Comment by eximius313** [comment]
So I think you could use this functionality: https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html and let both ```@Restrict``` and ```@Dynamic``` inherit common ```@Restriction``` (for example) in order to achieve annotation chaining like explained here: https://github.com/schaloner/deadbolt-2/issues/9#issue-5279749
or like this:
```
@Restrict("user")
@Restrict("user", handlerKey="additionalHandler")
public static Result bla
```
I would expect that this is ```AND``` relation.
Whichever handler fails first,  its ```onAuthFailure``` is fired and its response is returned
If handler succeeds next handler is examined.

**Comment by schaloner** [comment]
It's not quite that straight-forward, because that would affect how class-level and method-level constraints interact..  Right now, the easiest way to achieve this is to use a Dynamic restriction, and build the chain within it.

**Comment by eximius313** [comment]
by the way - if one would like to achieve ```OR``` relation instead of default ```AND```, then having something like this
```
	@Retention(RetentionPolicy.RUNTIME)
	@Target(value=ElementType.METHOD)
	@Repeatable(Restrictions.class)
	public static @interface Restriction{
		String value();
	}

	@Retention(RetentionPolicy.RUNTIME)
	@Target(value=ElementType.METHOD)
	public static @interface Restrictions{
		Restriction[] value();
		boolean or() default true;
	}
```
one could achieve ```AND``` relation using this syntax:
```
	@Restriction(value="A")
	@Restriction(value="B")
```
and for ```OR``` relation this syntax:
```
@Restrictions(value={@Restriction(value="A"), @Restriction(value="B")}, or=true)
```

**Comment by schaloner** [comment]
If you take a look at https://deadbolt-java.readme.io/v2.5/docs/composite-constraints you can see how to create composite constraints.  Once it's finalized in 2.5, I'll backport it to 2.4.

The Scala implementation is ongoing.

**Comment by schaloner** [comment]
The Scala version is now available too.  See https://deadbolt-scala.readme.io/v2.5/docs/composite-constraints for usage information.
